options:
  source:
    default: ppa:canonical-infoblox/stable
    type: string
    description: |
      Repository from which to install. Ex: ppa:canonical-infoblox/stable
  cloud-data-center-id:
    type: string
    default: '1'
    description: |
      An integer ID used for the data center. This is used to form the stanza
      name for the rest of the options. If you have multiple instances of
      OpenStack sharing the same Infoblox grid, this ID needs to be unique
      across the instances. The ID should start from 1 and increment by 1 as
      you add another Openstack instance. This ID is used to generate a unique
      ID for a network view that is cached in neutron database. Starting it
      with a very high number may exceed the max length of a network view id.
  grid-master-host:
    type: string
    default: ''
    description: |
      The IP address, hostname, or FQDN of the Grid Master (GM). Proxying is
      supported so this does not have to be the exact IP or hostname of the GM
      if you have a situation where you cannot reach the GM directly in your
      network. It can be any connection information that proxies to the GM.
  grid-master-name:
    type: string
    default: ''
    description: |
      The name of the Grid Master (GM) This has to be the exact GM name
      registered in the Infoblox grid.
  admin-user-name:
    type: string
    default: ''
    description: |
      The user name to use for the WAPI.
  admin-password:
    type: string
    default: ''
    description: |
      The password to use for the WAPI.
  wapi-version:
    type: string
    default: '2.3'
    description: |
      The WAPI version to use. WAPI Version 2.3 or later is supported.
      (NIOS version 7.3.x or later is supported)
  wapi-max-results:
    type: string
    default: '-1000'
    description: |
      The maximum number of objects to be returned by WAPI. If this is set to
      a negative number, WAPI will return an error when the number of returned
      objects would exceed the setting. If this is set to a positive number,
      the results will be truncated when necessary. The default is -1000.
      If you experience "Result set too large" error, increase this value.
  wapi-paging:
    type: boolean
    default: False
    description: |
      Enables paging to wapi calls by configuring wapi_paging = True, it uses
      wapi_max_results to set paging size of the wapi calls. If wapi_max_results
      is negative it will take paging size as 1000. The default is False.
  network-views:
    type: string
    default: 'default'
    description: |
      Comma separated list of participating network views on the target
      Infoblox server.
